import os

main_code = """import pygame\nimport argparse\nimport sys\n\nparser = argparse.ArgumentParser()\nparser.add_argument('--speed', type=int, default=5)\nparser.add_argument('--bg', type=str, default='black')\nargs, _ = parser.parse_known_args()\n\nWIDTH, HEIGHT = 800, 600\nBG_COLOR = (0, 0, 0) if args.bg == 'black' else (255, 255, 255)\nPADDLE_COLOR = (0, 255, 0)\nBALL_COLOR = (255, 0, 0)\nBRICK_COLOR = (0, 0, 255)\n\nclass Paddle:\n    def __init__(self):\n        self.rect = pygame.Rect(WIDTH // 2 - 60, HEIGHT - 40, 120, 15)\n    def draw(self, screen):\n        pygame.draw.rect(screen, PADDLE_COLOR, self.rect)\n    def move(self, dx):\n        self.rect.x += dx\n        if self.rect.left < 0: self.rect.left = 0\n        if self.rect.right > WIDTH: self.rect.right = WIDTH\n\nclass Ball:\n    def __init__(self, speed):\n        self.rect = pygame.Rect(WIDTH // 2, HEIGHT // 2, 15, 15)\n        self.dx = speed\n        self.dy = -speed\n    def draw(self, screen):\n        pygame.draw.ellipse(screen, BALL_COLOR, self.rect)\n    def move(self):\n        self.rect.x += self.dx\n        self.rect.y += self.dy\n        if self.rect.left < 0 or self.rect.right > WIDTH: self.dx *= -1\n        if self.rect.top < 0: self.dy *= -1\n\ndef start_game():\n    pygame.init()\n    screen = pygame.display.set_mode((WIDTH, HEIGHT))\n    pygame.display.set_caption('Arkanoid CI/CD')\n    clock = pygame.time.Clock()\n    paddle = Paddle()\n    ball = Ball(args.speed)\n    bricks = [pygame.Rect(15 + i * 78, 20 + j * 35, 70, 25) for i in range(10) for j in range(5)]\n    while True:\n        for event in pygame.event.get():\n            if event.type == pygame.QUIT:\n                pygame.quit()\n                sys.exit()\n        keys = pygame.key.get_pressed()\n        if keys[pygame.K_LEFT]: paddle.move(-8)\n        if keys[pygame.K_RIGHT]: paddle.move(8)\n        ball.move()\n        if ball.rect.colliderect(paddle.rect) and ball.dy > 0: ball.dy *= -1\n        hit_index = ball.rect.collidelist(bricks)\n        if hit_index != -1:\n            bricks.pop(hit_index)\n            ball.dy *= -1\n        if ball.rect.bottom > HEIGHT:\n            pygame.quit()\n            sys.exit()\n        screen.fill(BG_COLOR)\n        paddle.draw(screen)\n        ball.draw(screen)\n        for b in bricks: pygame.draw.rect(screen, BRICK_COLOR, b)\n        pygame.display.flip()\n        clock.tick(60)\n\nif __name__ == '__main__':\n    start_game()\n"""
with open('main.py', 'w', encoding='utf-8') as f: f.write(main_code)

with open('requirements.txt', 'w', encoding='utf-8') as f:
    f.write("pygame==2.5.2\npytest==8.1.1\npytest-html==4.1.1\nflake8==7.0.0\nflake8-html==0.4.3\n")

test_code = """import pytest\nfrom unittest.mock import patch, MagicMock\nimport sys\nsys.modules['pygame'] = MagicMock()\nimport main\n\n@pytest.fixture\ndef default_paddle(): return main.Paddle()\n\n@pytest.fixture\ndef default_ball(): return main.Ball(speed=5)\n\n@pytest.mark.physics\ndef test_ball_initial_speed(default_ball):\n    assert default_ball.dx == 5\n    assert default_ball.dy == -5\n\n@pytest.mark.physics\n@pytest.mark.parametrize("move_distance, expected_x", [(-10, 330), (10, 350), (0, 340)])\ndef test_paddle_movement(default_paddle, move_distance, expected_x):\n    default_paddle.rect.x = 340\n    default_paddle.move(move_distance)\n    assert default_paddle.rect.x == expected_x\n\n@patch('main.pygame.draw.rect')\ndef test_paddle_draw_calls_pygame(mock_draw_rect, default_paddle):\n    mock_screen = MagicMock()\n    default_paddle.draw(mock_screen)\n    mock_draw_rect.assert_called_once()\n"""
with open('test_main.py', 'w', encoding='utf-8') as f: f.write(test_code)

os.makedirs('.github/workflows', exist_ok=True)
yaml_code = """name: CI/CD Pipeline Test\non:\n  push:\n    branches: [ "main" ]\njobs:\n  test-and-lint:\n    runs-on: ubuntu-latest\n    steps:\n    - uses: actions/checkout@v4\n    - uses: actions/setup-python@v5\n      with:\n        python-version: '3.10'\n    - run: |\n        python -m pip install --upgrade pip\n        pip install -r requirements.txt\n    - run: flake8 . --format=html --htmldir=flake8_report || true\n    - run: pytest --html=pytest_report.html --self-contained-html\n    - uses: actions/upload-artifact@v4\n      if: always()\n      with:\n        name: pytest-html-report\n        path: pytest_report.html\n    - uses: actions/upload-artifact@v4\n      if: always()\n      with:\n        name: flake8-html-report\n        path: flake8_report/\n"""
with open('.github/workflows/ci.yml', 'w', encoding='utf-8') as f: f.write(yaml_code)
